theme: jekyll-theme-minimal
title: Luis Andrés Aponte San Román
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
logo: /assets/img/my_photo.png
# Configuración de estilos personalizados
sass:
  style: :compressed
