theme: jekyll-theme-minimal
title: Luis Andrés Aponte San Román
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
logo: /assets/img/my_photo.png

# Forzar a Jekyll a incluir la carpeta de inglés
include:
  - en

# Configuración de estilos personalizados
sass:
  style: :compressed
